import { FirebaseProvider } from "@/src/presentation/context/FirebaseContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import "./globals.css";
import { CartProvider } from "@/src/presentation/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50`}
      >
        <React.StrictMode>
          <FirebaseProvider>
            <CartProvider>
              {children}
            </CartProvider>
          </FirebaseProvider>
        </React.StrictMode>
      </body>
    </html>
  );
}
